#!/usr/bin/env bash

log() {
	echo $(date --rfc-3339=seconds) - $1
}

check_deal() {
	echo $(sonmcli worker ask-plan list | grep deal)
}

check_miner() {
	echo $(ps ax | grep miner | grep SCREEN)
}

hive_miner() {
	echo $(/hive/bin/miner $1)
}

wait_deal() {
        while true; do
		SONM_DEAL=$(check_deal)
		if [ -z "$SONM_DEAL" ]; then
			log "No deal in SONM, waiting"
			sleep 10
		else
			log "Deal opened: ${SONM_DEAL}, stopping miner"
			hive_miner stop
			watch_deal
		fi
	done
}

watch_deal() {
        while true; do
                SONM_DEAL=$(check_deal)
                if ! [ -z "$SONM_DEAL" ]; then
                        log "Deal is active ($SONM_DEAL), waiting"
			if ! [ -z "$(check_miner)" ]; then
			log "WARN - Miner is running for some reason, stopping miner"
			hive_miner stop
			fi
                        sleep 10
                else
                        log "Deal has been closed: starting miner"
                        hive_miner start
                        wait_deal
		fi
        done
}

export $(cat /etc/environment | grep -v "#")
MINER_STATUS=$(check_miner)
SONM_STATUS=$(check_deal)

if [ -z "$MINER_STATUS" ]; then
	log "Miner not running"
	if [ -z "$SONM_STATUS" ]; then
		log "There's no deal in SONM"
		wait_deal
	else
		log "There is the deal in SONM ($SONM_STATUS), waiting for deal finish"
		watch_deal
	fi
else
	log "Miner is running"
	if [ -z "$SONM_STATUS" ]; then
                log "There's no deal in SONM, waiting for the deal"
                wait_deal
        else
                log "There is the deal in SONM ($SONM_STATUS), stopping miner"
                hive_miner stop
		watch_deal
        fi
fi
